object ModuleDeps {
    const val common = ":common"
    const val di = ":core:di"
    const val api = ":core:api"
    const val cache = ":cache"
    const val domain = ":domain"
    const val apiResponse = ":model:apiresponse"
    const val entity = ":model:entity"
    const val data = ":data"
    const val assets = ":assets"
    const val navigation = ":navigation"
    const val list = ":feature:list"
    const val favourite = ":feature:favourite"
    const val settings = ":feature:settings"
}